apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ollama
data:
  nfs-path: "/storage/hd5/DB"
  server-ip: "10.1.1.6"
  storage: "10Gi"
  root-password: "password"
  
  my.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
    net_read_timeout = 360
    net_write_timeout = 360